
import type { Department, Doctor, Patient, Registration } from '@/lib/types';

export const departments: Department[] = [
  {
    id: 'dept-1',
    name: 'Cardiology',
    description: 'Deals with disorders of the heart.',
  },
  {
    id: 'dept-2',
    name: 'Orthopedics',
    description: 'Deals with the musculoskeletal system.',
  },
  {
    id: 'dept-3',
    name: 'General Medicine',
    description: 'General medical services for adults.',
  },
];

export const registrations: Registration[] = [
  {
    id: 'reg-1',
    name: 'Alice Johnson',
    age: 34,
    gender: 'Female',
    phone: '555-0101',
    email: 'alice.j@example.com',
    address: '123 Oak St, Greenwood',
    department: 'Cardiology',
    medicalCondition: 'Asthma',
  },
  {
    id: 'reg-2',
    name: 'Bob Williams',
    age: 45,
    gender: 'Male',
    phone: '555-0102',
    email: 'bob.w@example.com',
    address: '456 Pine St, Mapleton',
    department: 'Orthopedics',
    medicalCondition: 'High blood pressure',
  },
  {
    id: 'reg-3',
    name: 'Charlie Brown',
    age: 28,
    gender: 'Male',
    phone: '555-0103',
    email: 'charlie.b@example.com',
    address: '789 Birch St, Oceanview',
    department: 'General Medicine',
    medicalCondition: 'None',
  },
  {
    id: 'reg-4',
    name: 'Diana Prince',
    age: 29,
    gender: 'Female',
    phone: '555-0104',
    email: 'diana.p@example.com',
    address: '101 Maple Ave, Greenwood',
    department: 'Cardiology',
    medicalCondition: 'Allergies',
  },
    {
    id: 'reg-5',
    name: 'Edward Nygma',
    age: 52,
    gender: 'Male',
    phone: '555-0105',
    email: 'ed.n@example.com',
    address: '212 Riddle Rd, Mapleton',
    department: 'General Medicine',
    medicalCondition: 'Diabetes Type 2',
  },
];

export const patients: Patient[] = [
  {
    bookNumber: '12345',
    name: 'Nik',
    phone: '8390999999',
    age: 25,
    gender: 'Male',
    area: 'Hyderabad',
    tokenNumber: '1001',
    status: 'Waiting for Doctor',
    assignedDoctorId: 'doc-1',
  },
  {
    bookNumber: '12346',
    name: 'Priya Sharma',
    phone: '9876543210',
    age: 34,
    gender: 'Female',
    area: 'Delhi',
    tokenNumber: '1002',
    status: 'Waiting for Doctor',
    assignedDoctorId: 'doc-2',
  },
    {
    bookNumber: '12347',
    name: 'Amit Patel',
    phone: '9988776655',
    age: 45,
    gender: 'Male',
    area: 'Mumbai',
    tokenNumber: '1003',
    status: 'With Doctor',
    assignedDoctorId: 'doc-1',
  },
  {
    bookNumber: '12348',
    name: 'Sunita Singh',
    phone: '9123456789',
    age: 29,
    gender: 'Female',
    area: 'Bangalore',
    tokenNumber: '1004',
    status: 'Waiting for Lab',
  },
  {
    bookNumber: '12349',
    name: 'Rahul Kumar',
    phone: '9234567890',
    age: 52,
    gender: 'Male',
    area: 'Chennai',
    tokenNumber: '1005',
    status: 'Waiting for Pharmacy',
  },
];


export const doctors: Doctor[] = [
  { id: 'doc-1', name: 'Rama Rao', specialty: 'General Physician' },
  { id: 'doc-2', name: 'Siva Ramulu', specialty: 'ENT' },
  { id: 'doc-3', name: 'Prabhavathi', specialty: 'Gynec' },
  { id: 'doc-4', name: 'Shailaja', specialty: 'Gynec' },
  { id: 'doc-5', name: 'Somaraju', specialty: 'Pediatrician' },
  { id: 'doc-6', name: 'Anshitha', specialty: 'Gen.physician' },
  { id: 'doc-7', name: 'Prabavathi', specialty: 'Gynecologist' },
  { id: 'doc-8', name: 'Dr. Dileep', specialty: 'G.Physician' },
  { id: 'doc-9', name: 'Guest 1', specialty: 'General' },
  { id: 'doc-10', name: 'Guest 2', specialty: 'General' },
  { id: 'doc-11', name: 'Dr. Arun', specialty: 'Ortho' },
  { id: 'doc-12', name: 'Dr. Bhargav', specialty: 'General Physician' },
  { id: 'doc-13', name: 'Repeated', specialty: 'Repeated' },
  { id: 'doc-14', name: 'Dr. Karan', specialty: 'Orthopedic' },
];
